import { StyleSheet, Dimensions } from 'react-native';
import colors from '../../style/colors';
import * as Utils from '../../style/Utils';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F1F1F1',
  },
  paddingRight: {
    paddingRight: Utils.pd(0.3),
    paddingBottom: Utils.pd(0.1),
  },
  containerLogo: {
    paddingTop: Utils.wp(1),
    alignItems: 'flex-end',
  },
  containerLogoTab: {
    paddingTop: Utils.wp(1),
    alignItems: 'center',
  },
  containerPartOrder: {
    flexDirection: 'row',
    flex: 1,
    paddingBottom: Utils.wp('10%'),
    borderRadius: Utils.wp(10),
  },
  containerDash: {
    flex: 0,
    width: Utils.hp(140),
    height: Utils.hp(140),
    padding: Utils.wp(5),
    marginRight: Utils.wp(5),
    marginLeft: Utils.wp(20),
    marginTop: Utils.wp(10),
    backgroundColor: '#cacaca',
    flexDirection: 'column',
    overflow: 'hidden',
  },
  brandImage: {
    resizeMode: 'contain',
    alignSelf: 'flex-start',
    justifyContent: 'flex-start',
    height: Utils.hp(18),
    width: Utils.wp(80),
    marginVertical: Utils.hp(5),
  },
  brandUnitContainer: {
    flex: 3,
    flexDirection: 'row',
    alignItems: 'center',
  },
  unitContainer: {
    flex: 0,
    alignSelf: 'flex-end',
  },
  vehicleImage: {
    flex: 1,
    resizeMode: 'contain',
    width: Utils.wp(60),
    height: Utils.hp(80),
    position: 'absolute',
    bottom: -5,
    right: Utils.wp(-10),
    zIndex: -2,
    opacity: 0.8,
  },
  containerPromotion: {
    flex: 1,
    width: Dimensions.get('window').width - 40,
    height: Dimensions.get('window').height / 4,
    borderRadius: Utils.wp(20),
    padding: Utils.wp(10),
    resizeMode: 'contain',
  },

  containerRotate: {
    flex: 1,
    flexDirection: Dimensions.get('window').height > 1000 ? 'column' : 'row',
  },
  containerTotal: {
    borderTopLeftRadius: Utils.wp(6),
    borderBottomLeftRadius: Utils.wp(6),
    width: Utils.wp('30%'),
    height: Utils.wp(108),
    backgroundColor: colors.white,
  },
  containerOpen: {
    width: Utils.wp('25%'),
    height: Utils.wp(108),
    backgroundColor: colors.yellow,
    justifyContent: 'center',
  },
  containerOpenMid: {
    width: Utils.wp('30%'),
    height: Utils.wp(108),
    backgroundColor: colors.yellow,
    justifyContent: 'center',
  },
  containerOpenLarge: {
    width: Utils.wp('35%'),
    height: Utils.wp(108),
    backgroundColor: colors.yellow,
    justifyContent: 'center',
  },
  containerClosedMid: {
    borderTopRightRadius: Utils.wp(6),
    borderBottomRightRadius: Utils.wp(6),
    width: Utils.wp('30%'),
    height: Utils.wp(108),
    backgroundColor: colors.green,
    justifyContent: 'center',
    marginRight: Utils.pd(1),
  },
  containerClosed: {
    borderTopRightRadius: Utils.wp(6),
    borderBottomRightRadius: Utils.wp(6),
    width: Utils.wp('25%'),
    height: Utils.wp(108),
    backgroundColor: colors.green,
    justifyContent: 'center',
    marginRight: Utils.pd(1),
  },
  containerClosedLarge: {
    borderTopRightRadius: Utils.wp(6),
    borderBottomRightRadius: Utils.wp(6),
    width: Utils.wp('35%'),
    height: Utils.wp(108),
    backgroundColor: colors.green,
    justifyContent: 'center',
    marginRight: Utils.pd(1),
  },
  headerClosed: {
    flex: 1,
    flexDirection: 'row',
  },
  containerList: {
    paddingLeft: Utils.wp(20),
    paddingRight: Utils.wp(20),
  },
  contentImagerOrder: {
    alignItems: 'flex-start',
    paddingTop: Utils.wp(1),
    paddingLeft: Utils.wp(10),
  },
  imageOrder: {
    resizeMode: 'contain',
    marginTop: Utils.wp(3),
    paddingLeft: Utils.wp(7),
    height: Dimensions.get('window').height / 30,
    width: Dimensions.get('window').width / 30,
    alignItems: 'center',
  },
  logo: {
    flex: 1,
    width: Utils.wp('100%'),
    height: Utils.wp('80%'),
    resizeMode: 'contain',
  },
  logoNotification: {
    marginRight: Utils.wp(10),
    marginTop: Utils.wp(-5),
    width: Utils.wp(25),
    resizeMode: 'contain',
  },
  logoCart: {
    marginRight: Utils.wp(10),
    width: Utils.wp(27),
    resizeMode: 'contain',
  },
  logoUTTab: {
    marginTop: Utils.wp(5),
    width: Utils.wp(155),
    marginBottom: Utils.wp(-15),
    resizeMode: 'contain',
  },
  logoDropDown: {
    width: Utils.wp(12),
    height: Utils.wp(7),
    resizeMode: 'contain',
  },
  flatlistBox: {
    flex: 1,
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'space-around',
    backgroundColor: '#fff',
  },
  flatlistBox2: {
    flex: 1,
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'space-around',
  },
  flatlistBoxTab: {
    flex: 1,
    flexDirection: 'column',
    marginLeft: Utils.wp(20),
  },
  isiFlatlistBox: {
    paddingRight: Utils.wp(5),
  },
  logoClose: {
    marginLeft: Utils.wp(20),
    width: Utils.wp(18),
    height: Utils.wp(20),
    resizeMode: 'contain',
  },
  thumbnailContent: {
    width: Utils.wp(65),
    height: Utils.wp(65),
  },
  column: {
    flex: 1,
    alignItems: 'center',
    flexDirection: 'column',
  },
  column2: {
    flex: 1,
    justifyContent: 'center',
    flexDirection: 'row',
    paddingLeft: Utils.wp(20),
    paddingRight: Utils.wp(20),
    paddingBottom: Utils.wp(10),
  },
  columnViewAll: {
    flex: 1,
    justifyContent: 'flex-end',
    paddingBottom: Utils.wp(10),
  },
  columnFeed: {
    height: Utils.wp(200),
    backgroundColor: colors.white,
  },
  loc: {
    flex: 1,
    alignItems: 'flex-end',
  },
  logoText: {
    flex: 1,
    marginRight: Utils.wp(20),
    color: '#212121',
    fontSize: Utils.fixedFontSize(20),
    fontWeight: 'bold',
    textAlign: 'left',
    paddingVertical: Utils.wp(2),
    fontFamily: 'SFUIText-Regular',
  },
  logoTextViewAll: {
    flex: 1,
  },
  logoTextOrder: {
    marginRight: Utils.wp(20),
    marginLeft: Utils.wp(20),
    paddingTop: Utils.wp(7),
    color: '#212121',
    fontSize: Utils.fixedFontSize(20),
    fontWeight: 'bold',
    textAlign: 'left',
    paddingVertical: Utils.wp(2),
    fontFamily: 'SFUIDisplay-Medium',
  },
  paddingTimeline: {
    flex: 0,
    paddingLeft: Utils.wp(20),
    paddingRight: Utils.wp(10),
  },
  paddingLeftTimeline: {
    paddingLeft: Utils.wp(23),
  },
  textChild: {
    marginLeft: Utils.wp(10),
    paddingBottom: Utils.wp(10),
    color: colors.gray,
    fontSize: Utils.fixedFontSize(14),
    textAlign: 'left',
    paddingVertical: Utils.wp(2),
    fontFamily: 'SFUIDisplay-Medium',
  },
  textYears: {
    marginLeft: Utils.wp(20),
    paddingBottom: Utils.wp(10),
    color: colors.black,
    fontSize: Utils.fixedFontSize(14),
    textAlign: 'left',
    paddingVertical: Utils.wp(2),
    fontFamily: 'SFUIDisplay-Thin',
  },
  textUnits: {
    color: '#fff',
    fontSize: Utils.fixedFontSize(16),
    textAlign: 'center',
    fontFamily: 'SFUIDisplay-Medium',
  },
  textChildList: {
    color: colors.gray,
    fontSize: Utils.fixedFontSize(12),
    textAlign: 'left',
    paddingLeft: Utils.wp(10),
    fontFamily: 'SFUIDisplay-Medium',
  },
  textNumber: {
    fontWeight: '900',
    paddingTop: Utils.wp(10),
    fontSize: Dimensions.get('window').height >= 1000 ? Utils.fixedFontSize(18) : Utils.fixedFontSize(21),
    fontFamily: 'SFUIDisplay-Semibold',
  },
  fontTotalOrder: {
    fontSize: Utils.fixedFontSize(12),
    paddingLeft: Utils.wp(5),
    marginTop: Utils.wp(2),
    color: '#000',
  },
  textAmountOrder: {
    fontFamily: 'SFUIDisplay-Semibold',
    fontSize: Utils.fixedFontSize(24),
    textAlign: 'left',
    paddingLeft: Utils.wp(5)
  },
  fontOpenRotate: {
    fontSize: Utils.fixedFontSize(12),
    marginLeft: Dimensions.get('window').height > 1000 ? Utils.wp(5) : Utils.wp('5%'),
    paddingTop: Utils.wp(20),
    textAlign: 'left',
    color: '#000',
    transform: Dimensions.get('window').height > 1000 ? [{ rotate: '0deg' }] : [{ rotate: '270deg' }],
  },
  fontOrderRotate: {
    fontSize: Utils.fixedFontSize(14),
    marginLeft: Dimensions.get('window').height > 1000 ? Utils.wp(5) : 0,
    paddingTop: Utils.wp(2),
    textAlign: 'left',
    color: '#000',
    transform: Dimensions.get('window').height > 1000 ? [{ rotate: '0deg' }] : [{ rotate: '270deg' }],
  },
  titleAll: {
    flex: 1,
    alignItems: 'flex-end',
    marginRight: Utils.wp(2),
    paddingTop: Utils.wp(5),
    color: '#212121',
    fontSize: Utils.fixedFontSize(16),
    fontWeight: 'bold',
    textAlign: 'right',
    paddingVertical: Utils.wp(2),
    fontFamily: 'SFUIText-Regular',
  },
  titlePromotion: {
    flex: 1,
    alignItems: 'flex-end',
    marginRight: Utils.wp(10),
    color: '#212121',
    fontSize: Utils.fixedFontSize(13),
    textAlign: 'right',
    fontFamily: 'SFUIDisplay-Semibold',
  },
  textDate: {
    fontFamily: 'SFUIText-Regular',
    color: '#898989',
    fontSize: Utils.fixedFontSize(12),
  },
  textFooterTimeline: {
    marginTop: Utils.wp(4),
    fontFamily: 'SFUIText-Regular',
    color: '#000000',
    fontSize: Utils.fixedFontSize(12),
  },
  spinnerTextStyle: {
    color: '#FFF',
    fontSize: Utils.fixedFontSize(12),
  },
  item: {
    width: Utils.wp(100),
  },
  imageDash: {
    marginLeft: Dimensions.get('window').height > 1000 ? Utils.wp(-5) : Utils.wp(0),
    resizeMode: 'contain',
    width: Utils.hp(90),
    height: Utils.hp(30),

  },
  imageAll: {
    marginLeft: Dimensions.get('window').height > 1000 ? Utils.wp(-10) : Utils.wp(-15),
    resizeMode: 'contain',
    width: Utils.hp(70),
    height: Utils.hp(25),
  },
  bottomModal: {
    justifyContent: 'flex-end',
    width: Dimensions.get('window').width,
    height: Dimensions.get('window').height,
    margin: 0,
  },
  modalContent: {
    backgroundColor: 'white',
    paddingBottom: Utils.wp(10),
    borderRadius: Utils.wp(4),
    width: Dimensions.get('window').width,
    height: '100%',
    borderColor: 'rgba(0, 0, 0, 0.1)',
  },
  radio: {
    justifyContent: 'space-evenly',
    color: colors.yellow800,
    padding: Utils.wp(3),
  },
  radioALL: {
    padding: Utils.wp(3),
    marginTop: Utils.wp(10),
    justifyContent: 'space-evenly',
    color: colors.yellow800,
  },
  flatview: {
    justifyContent: 'space-evenly',
  },
  cardList: {
    flex: 0,
    marginRight: Utils.wp(15),
    marginLeft: Utils.wp(5),
    padding: Utils.wp(10),
    height: Utils.wp(50),
    borderColor: colors.black,
    backgroundColor: '#fff',
    borderRadius: Utils.wp(5),
  },
  cardListFinancial: {
    marginRight: Utils.wp(15),
    marginLeft: Utils.wp(5),
    padding: Utils.wp(10),
    height: Utils.wp(50),
    borderColor: colors.black,
    backgroundColor: '#fff',
    borderRadius: Utils.wp(5),
    flexDirection: 'row'
  },
  cardListStatusContainer: {
    flex: 1, 
    flexDirection: 'row', 
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  date: {
    color: 'black',
    fontSize: Utils.fixedFontSize(14),
    fontFamily: 'SFProText-Regular',
    fontWeight: 'bold',
  },
  imageContainer: {
    flex: 1,
    marginBottom: Platform.select({ ios: 0, android: 1 }), // Prevent a random Android rendering issue
    backgroundColor: 'white',
    borderRadius: 8,
  },
  containerLoading: {
    flex: 1,
    justifyContent: 'center',
  },
  horizontalLoading: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    padding: Utils.wp(10),
  },
  headerModelEmail: {
    marginTop: Utils.wp(10),
    justifyContent: 'center',
    flexDirection: 'column',
    alignItems: 'flex-start',
  },
  headerSendEmail: {
    flex: 0,
    justifyContent: 'center',
    alignItems: 'flex-start',
    flexDirection: 'row',
  },
  viewAll: {
    flex: 1,
    flexDirection: 'column',
    alignItems: 'flex-end',
    width: Utils.wp(80),
  },
  imageCheck: {
    marginTop: Utils.wp(4),
    width: Utils.wp(25),
    height: Utils.wp(25),
    resizeMode: 'contain',
  },
  buttonTicket: {
    borderBottomLeftRadius: Utils.wp(5),
    borderBottomRightRadius: Utils.wp(5),
    borderTopLeftRadius: Utils.wp(5),
    borderTopRightRadius: Utils.wp(5),
    width: Utils.wp(100),
    height: Utils.wp(25),
    justifyContent: 'center',
    backgroundColor: '#76D672',
    alignContent: 'flex-end'
  },
  containerTicket: {
    flex: 1,
    backgroundColor: '#fff',
    flexDirection: 'column',
    paddingLeft: Utils.wp(20),
    paddingRight: Utils.wp(20),
    paddingBottom: Utils.wp(10),
    paddingTop: Utils.wp(10),
  },
  childFinancial: {
    color: 'rgba(69, 69, 69, 0.7)',
    fontFamily: 'SFUIText-Regular',
    fontSize: Utils.fixedFontSize(11),
    letterSpacing: 0.5,
    lineHeight: 16
  },
  childTicket: {
    fontFamily: 'SFUIText-Regular',
    fontSize: Utils.fixedFontSize(12)
  },
  titleMyTicket: {
    fontFamily: 'SFProText-Regular',
    fontSize: Utils.fixedFontSize(16),
    fontWeight: 'bold'
  },
  headerContainerTicket: {
    flex: 1,
    justifyContent: 'center',
    paddingRight: Utils.wp(10),
    flexDirection: 'column',
    marginTop: Utils.wp(10)
  },
  imageUtCall: {
    width: Utils.wp(70),
    height: Utils.wp(90),
    resizeMode: 'contain'
  },
  titleButtonTicket: {
    textAlign: 'center',
    fontSize: Utils.fixedFontSize(10),
    color: "#fff",
    fontFamily: 'SFUIText-Regular',
  },
  textLocation: {
    fontSize: Utils.fixedFontSize(18),
    fontFamily: 'SFUIText-Regular',
    marginLeft: Utils.wp(-20),
  },
  textLocationSelected: {
    fontSize: Utils.fixedFontSize(18),
    fontFamily: 'SFUIText-Bold',
    marginLeft: Utils.wp(-20),
  },
  slide1: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#9DD6EB',
  },
  slide2: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#97CAE5',
  },
  slide3: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#92BBD9',
  },
  text: {
    color: '#fff',
    fontSize: Utils.fixedFontSize(16),
    fontWeight: 'bold',
  },
  swiperView: {
    width: Dimensions.get('window').width,
    height: Dimensions.get('window').width / 2,
  },
  imagePromotion: {
    width: Dimensions.get('window').width - 40,
    height: Dimensions.get('window').width / 2,
    resizeMode: 'contain',
    marginRight: Utils.wp(40),
    borderTopRightRadius: 20,
    borderBottomRightRadius: 20,
    borderTopLeftRadius: 20,
    borderBottomLeftRadius: 20,
  },
  swiperSS: {
    width: Dimensions.get('window').width * 0.8,
    height: Dimensions.get('window').height,
  },
  imageSS: {
    width: Dimensions.get('window').width * 0.8,
    height: Dimensions.get('window').height,
    resizeMode: 'contain',
    marginRight: Utils.wp(50),
  },
  promotionSS: {
    justifyContent: 'center',
    alignContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    // height: Dimensions.get('window').height,
    // width: Dimensions.get('window').width,
  },
  promotionView: {
    paddingLeft: Utils.wp(10),
    paddingRight: Utils.wp(10),
    flexDirection: 'column',
  },
  isiPromotionView: {
    paddingLeft: 10,
    paddingRight: 20,
  },
  bottom: {
    bottom: 0,
    position: 'absolute',
  },
  cardChangeUnit: {
    backgroundColor: '#de0046',
    width: Dimensions.get('window').width,
    height: Utils.wp(50),
    flexDirection: 'row',
    alignItems: 'center',
  },
  unitChange: {
    flex: 2,
    textAlign: 'center',
    color: '#FFFFFF',
    fontSize: Utils.fixedFontSize(12),
    marginLeft: Utils.wp(10),
  },
  unitChange2: {
    flex: 1,
    textAlign: 'center',
    color: '#FFFFFF',
    fontSize: Utils.fixedFontSize(14),
  },
  containerListChart: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFF',
    paddingLeft: Utils.wp(20),
    paddingRight: Utils.wp(20)
  },
  badgeGreen: {
    flex: 0,
    alignItems: 'center',
    backgroundColor: colors.greenOperate,
    borderRadius: Utils.wp(10),
    width: Utils.wp(12),
    height: Utils.wp(12),
    marginTop: Utils.wp(5),
    marginRight: Utils.wp(10)
  },
  badgeYellow: {
    flex: 0,
    alignItems: 'center',
    backgroundColor: colors.yellow,
    borderRadius: Utils.wp(10),
    width: Utils.wp(12),
    height: Utils.wp(12),
    marginTop: Utils.wp(5),
    marginRight: Utils.wp(10)
  },
  badgeOrange: {
    flex: 0,
    alignItems: 'center',
    backgroundColor: '#FFA439',
    borderRadius: Utils.wp(10),
    width: Utils.wp(12),
    height: Utils.wp(12),
    marginTop: Utils.wp(5),
    marginRight: Utils.wp(10)
  },
  badgeRed: {
    flex: 0,
    alignItems: 'center',
    backgroundColor: '#F47B7F',
    borderRadius: Utils.wp(10),
    width: Utils.wp(12),
    height: Utils.wp(12),
    marginTop: Utils.wp(5),
    marginRight: Utils.wp(10)
  },
  badgeChart: {
    flexDirection: 'row',
    marginBottom: Utils.wp(10)
  },
  textBadge: {
    fontFamily: 'SFUIDisplay-Bold',
    fontSize: Utils.fixedFontSize(12)
  },
  textFinancial: {
    paddingTop: Utils.wp(7),
    color: '#A8A8A8',
    fontSize: Utils.fixedFontSize(12),
    fontWeight: 'bold',
    textAlign: 'right',
    fontFamily: 'SFUIDisplay-Medium',
    alignItems: 'flex-end'
  },
  textMyFinancial: {
    paddingTop: Utils.wp(7),
    color: '#212121',
    fontSize: Utils.fixedFontSize(18),
    fontWeight: 'bold',
    textAlign: 'left',
    fontFamily: 'SFUIDisplay-Medium',
  },
  containerFinancial: {
    flex: 1,
    backgroundColor: '#fff',
    flexDirection: 'column',
    paddingLeft: Utils.wp(20),
    paddingRight: Utils.wp(20),
    paddingTop: Utils.wp(10),
  },
  imageFinancial: {
    width: Utils.wp(50),
    height: Utils.wp(50),
    position: 'absolute'
  },
  cardError: {
    alignContent: 'center',
    flex: 0,
    marginBottom: Utils.wp(20),
    paddingBottom: Utils.wp(10),
    borderRadius: Utils.wp(10),
    backgroundColor: 'rgba(244, 123, 127, 0.04)',
},
  boxFinancial: {
    marginLeft: Utils.wp(10),
    marginTop: Utils.wp(10),
    marginRight: Utils.wp(10),
    marginBottom: Utils.wp(8)
  },
  rowMyFinancial: {
    flexDirection: 'row',
    marginBottom: Utils.wp(10)
  },
  rowAllFinancial: {
    flex: 1,
    justifyContent: 'flex-end',
    alignItems: 'center',
    flexDirection: 'row'
  },
  boxDropDown: {
    flex: 0,
    justifyContent: 'center',
    marginTop: Utils.wp(10)
  },
  textDetail: {
    fontWeight: '700',
    fontSize: Utils.fixedFontSize(16),
    fontFamily: 'SFUIText-Regular',
  },
  viewAllDetail: {
    color: ' rgba(0, 0, 0, 0.75)',
    fontSize: Utils.fixedFontSize(11),
    fontFamily: 'SFUIText-Regular',
    fontWeight: '500'
  },
  rowDetailLeft: {
    flex: 1,
    alignItems: 'flex-start',
    marginTop: Utils.wp(10),
  },
  rowDetailRight: {
    flex: 1,
    alignItems: 'flex-end',
    marginTop: Utils.wp(15),
  },
  textPieChart: {
    fontFamily: 'SFUIDisplay-Bold',
    fontSize: Utils.fixedFontSize(25),
    textAlign: 'center',
    textAlignVertical: 'center',
  },
  rowBadge: {
    flex: 1,
    alignItems: 'flex-start',
    flexDirection: 'column',
    marginLeft: Utils.wp(40),
    marginTop: Utils.wp(20),
    marginBottom: Utils.wp(10)
  },
  textPositionChart: {
    width: Utils.wp(115),
    position: 'absolute',
    alignItems: 'center',
    flexDirection: 'column',
  },
  inputContainerStyle: {
    flex: 1,
    backgroundColor: colors.grayMedium,
    borderRadius: 10,
  },
  containerStyle: {
    backgroundColor: '#fff',
    borderBottomWidth: 0,
    borderTopWidth: 0,
    flex: 1,
  },
  buttonBeli: {
    flex: 0,
    height: Utils.wp(35),
    width: Utils.hp(140),
    marginTop: Utils.wp(5),
    marginLeft: Utils.wp(20),
    borderRadius: 20,
    backgroundColor: '#6d358c',
    alignItems: 'center',
    justifyContent: 'center',
  },
  textButton: {
    color: '#fff',
    fontSize: Utils.fixedFontSize(12),
    textAlign: 'center',
    fontFamily: 'SFUIText-Bold',
    fontWeight: 'bold',
  },
  buttonSearch: {
    flex: 1,
    height: Utils.wp(37),
    marginBottom: Utils.wp(5),
    backgroundColor: '#f1f1f1',
    alignItems: 'center',
    justifyContent: 'center',
  },
  lineStyle1: {
    borderWidth: Utils.wp(1),
    borderColor: '#cacaca',
    borderRadius: 20,
    marginTop: Utils.wp(4),
    marginBottom: Utils.wp(4),
  },
  lineStyle2: {
    borderWidth: Utils.wp(1),
    borderColor: '#ededed',
    borderRadius: Utils.wp(10),
    marginBottom: Utils.wp(10),
  },
  imageSortHeader: {
    width: Utils.wp(20),
    resizeMode: 'contain',
    marginTop: Utils.wp(2)
  },
  headerModelContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  headerBack: {
    flex: 0,
  },
  headerFilter: {
    flex: 1,
    alignItems: 'center',
  },
  textTitle: {
    marginTop: Utils.wp(20),
    marginRight: Utils.wp(20),
    marginBottom: Utils.wp(20),
    fontSize: Utils.fixedFontSize(14),
    fontFamily: 'SFUIDisplay-Bold',
  },
  textKategori: {
    marginLeft: Utils.wp(20),
    fontSize: Utils.fixedFontSize(14),
    fontFamily: 'SFUIDisplay-Bold',
  },
  textRegist: {
    flex: 1,
    marginTop: Utils.wp(10),
    marginBottom: Utils.wp(10),
    marginLeft: Utils.wp(20),
    fontSize: Utils.fixedFontSize(16),
    fontFamily: 'SFUIDisplay-Medium',
  },
  textHargaMin: {
    flex: 1,
    fontSize: Utils.fixedFontSize(14),
    fontFamily: 'SFUIDisplay-Medium',
    marginLeft: Utils.wp(20)
  },
  textHargaMax: {
    flex: 1,
    fontSize: Utils.fixedFontSize(14),
    fontFamily: 'SFUIDisplay-Medium',
    textAlign: 'right',
    marginRight: Utils.wp(20)
  },
  valueHargaMin: {
    marginTop: Utils.wp(-70),
    flex: 1,
    fontSize: Utils.fixedFontSize(14),
    fontFamily: 'SFUIDisplay-Medium',
    marginLeft: Utils.wp(20),
    fontWeight: 'bold',
  },
  valueHargaMax: {
    marginTop: Utils.wp(-70),
    flex: 1,
    fontSize: Utils.fixedFontSize(14),
    fontFamily: 'SFUIDisplay-Medium',
    textAlign: 'right',
    marginRight: Utils.wp(20),
    fontWeight: 'bold',
  },
  logInButton: {
    flex: 1,
    height: Utils.wp(40),
    paddingLeft: Utils.wp(5),
    alignItems: 'center',
    justifyContent: 'center',
  },
  textDaftar: {
    color: '#4a9d8c',
    fontSize: Utils.fixedFontSize(12),
    fontFamily: 'SFUIDisplay-Medium',
    textDecorationLine: 'underline',
    marginLeft: Utils.wp(20),
  },
  headerModel: {
    flexDirection: 'row',
    alignItems: 'center',
    marginLeft: Utils.wp(10),
  },
  headerBorderItemActive: {
    flexDirection: 'row',
    alignItems: 'center',
    textAlign: 'center',
    borderRadius: Utils.wp(20),
    borderWidth: Utils.wp(3),
    borderColor: '#6d358c',
    backgroundColor: '#6d358c',
    paddingHorizontal: Utils.wp(20),
    paddingVertical: Utils.wp(7),
    margin: Utils.wp(10),
  },
  headerBorderItem: {
    flexDirection: 'row',
    alignItems: 'center',
    textAlign: 'center',
    borderRadius: Utils.wp(20),
    borderWidth: Utils.wp(3),
    borderColor: '#e8e6e6',
    paddingHorizontal: Utils.wp(20),
    paddingVertical: Utils.wp(7),
    margin: Utils.wp(10),
  },
  headerFilterItem: {
    flex: 0,
    alignItems: 'center',
    flexDirection: 'row',
  },
  sortOptionText: {
    fontSize: Utils.fixedFontSize(16),
    color: '#212121'
  },
  sortOptionTextActive: {
    fontSize: Utils.fixedFontSize(16),
    color: '#fff'
  },
});
